### ISSUE TITLE
Pre-installed Python Option

### ISSUE THREAD

**Issue by quasiben** [blaze/rambling#120]
Currently, dask-yarn only works with envs shipped to or cached in HDFS.  Occasionally, all the requisite packages and dependencies are in place on the cluster.  If I am fortunate to work on a pre-configured cluster for dask-yarn I should be allowed to refer to the pre-configured Python binary and use any HDFS based environments. 

My proposal would is to add another option: `cluster_python_prefix` or `pythonprefix` or another name, to the `DaskYARNCluster` constructor and pass that string to the knit command:

```python
pref = self.pythonprefix
if self.env:
    bn = os.path.basename(self.env)
    pathsep = '/'  # assume execution is always on posix
    pref = pathsep.join([bn, os.path.splitext(bn)[0]])  # like myenv.zip/myenv
command = ('{pref}/bin/python {pref}/bin/dask-worker....')
```

**Comment by martindurant** [comment]
Certainly I think this is useful.
We need to tell the scala code NOT to upload anything (there is already a path for this) and to pass the python executable path through rather than constructing one.

**Comment by jcrist** [comment]
Skein (https://jcrist.github.io/skein/) allows for a more flexible way of describing applications to run on YARN. Dask-Yarn has been rewritten to use skein (http://dask-yarn.readthedocs.io/), and can accept a generic skein specification to start dask. The above can be achieved by:


```
# spec.yaml
name: dask
queue: default
max_attempts: 1

services:
    dask.scheduler:
        resources:
            memory: 512
            vcores: 1
        commands:
            - /path/to/dask-yarn-scheduler

    dask.worker:
        instances: 0
        max_restarts: 2
        resources:
            memory: 512
            vcores: 1
        depends:
            - dask.scheduler
        commands:
            - /path/to/dask-yarn-worker 1 --memory_limit 512MB
```

```python
from dask_yarn import YarnCluster

cluster = YarnCluster.from_specification('spec.yaml')
cluster.scale(10)
```

Closing, development has moved to https://github.com/dask/dask-yarn.
